import { Server, EVENTS } from '@tus/server';
import { FileStore } from '@tus/file-store';
import { v4 as uuidv4 } from 'uuid';
import path from 'path';
import { existsSync, unlinkSync } from 'fs';
import logger from '../logger/index.js';
import { uploadsDir } from '../lib/upload.js';
import { addUpload, getCustomCountries } from '../data/store.js';
import { COUNTRIES, buildWeeks, weekUploadCutoff } from '../data/constants.js';
import { recordUpload } from '../monitoring/metrics.js';
import { broadcastNotification } from './webpush.js';
import { io } from '../app.js';
import { safeEqual } from '../middleware/auth.js';

const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;

const isValidWeek = (weekId) => buildWeeks().some((w) => w.id === weekId);
const isValidCountry = (countryId) =>
  COUNTRIES.some((c) => c.id === countryId) ||
  getCustomCountries().some((c) => c.id === countryId);

function checkUploadCutoff(weekId) {
  const cutoff = weekUploadCutoff(weekId);
  if (!cutoff) return null;
  if (new Date() > cutoff) {
    const err = new Error('Date limite d\'envoi dépassée');
    err.status_code = 423;
    err.body = 'Délai dépassé : les uploads pour cette semaine sont clôturés depuis dimanche 17h30.';
    return err;
  }
  return null;
}

export const tusServer = new Server({
  path: '/api/tus',
  datastore: new FileStore({ directory: uploadsDir }),
  namingFunction: (req) => {
    // Generate UUID with timestamp to guarantee uniqueness and trace uploads
    return `${Date.now()}-${uuidv4()}`;
  },
  onUploadCreate: async (req, res, upload) => {
    // Authentification & Validation
    const meta = upload.metadata || {};
    const weekId = meta.weekId;
    const countryId = meta.countryId;
    const adminToken = meta.adminPassword;

    if (!isValidWeek(weekId) || !isValidCountry(countryId)) {
      throw { status_code: 404, body: 'Week ou Country invalide' };
    }

    const isAdmin = safeEqual(adminToken, ADMIN_PASSWORD);
    if (!isAdmin) {
      const cutoffErr = checkUploadCutoff(weekId);
      if (cutoffErr) throw cutoffErr;
    }

    return res;
  },
  onUploadFinish: async (req, res, upload) => {
    const meta = upload.metadata || {};
    const weekId = meta.weekId;
    const countryId = meta.countryId;
    const filename = upload.id; // Generated by namingFunction
    const originalName = meta.name || 'Unknown.mp4';
    const reportage = meta.reportage || null;
    const fileType = meta.filetype || 'application/octet-stream';
    const fileSize = upload.size;

    const isScript = fileType.startsWith('text/') || fileType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    const isImage = fileType.startsWith('image/');
    const isAudio = fileType.startsWith('audio/');

    const fileData = {
      id: uuidv4(),
      name: originalName,
      filename: filename,
      type: isScript ? 'script' : isImage ? 'image' : isAudio ? 'audio' : 'video',
      size: `${(fileSize / (1024 * 1024)).toFixed(1)} MB`,
      status: 'pending',
      reportage,
      uploadedAt: new Date().toISOString(),
    };

    try {
      addUpload(weekId, countryId, fileData);
      recordUpload(1000, true); // Mock duration since we don't have start time across chunks
      logger.uploadReceived(weekId, countryId, originalName, fileData.size);

      logger.info('TUS Upload completed and persisted', {
        context: {
          weekId,
          countryId,
          filename: originalName,
          fileId: fileData.id,
          type: fileData.type,
          size: fileData.size,
        },
      });

      broadcastNotification({
        title: 'Nouveau fichier reçu',
        body: `Un fichier a été envoyé via l'envoi sécurisé par ${countryId} pour la semaine ${weekId}.`,
        url: `/?week=${weekId}`
      }).catch(err => logger.error('Push notification failed', { error: err.message }));

      io?.emit('upload_update', { weekId, countryId });

    } catch (storeErr) {
      logger.uploadFailed(weekId, countryId, originalName, storeErr);
      // Clean up file if DB fails
      const filePath = path.join(uploadsDir, filename);
      if (existsSync(filePath)) {
        unlinkSync(filePath);
      }
    }
    return res;
  }
});
