import { Server, EVENTS } from '@tus/server';
import { FileStore } from '@tus/file-store';
import { v4 as uuidv4 } from 'uuid';
import path from 'path';
import { existsSync, unlinkSync } from 'fs';
import logger from '../logger/index.js';
import { uploadsDir, MAX_FILE_SIZE, ALLOWED_EXTENSIONS } from '../lib/upload.js';
import { addUpload, getCustomCountries } from '../data/store.js';
import { COUNTRIES, buildWeeks, weekUploadCutoff } from '../data/constants.js';
import { recordUpload } from '../monitoring/metrics.js';
import { broadcastNotification } from './webpush.js';
import { io } from '../app.js';
import { safeEqual, normalizeToken } from '../middleware/auth.js';

const isValidWeek = (weekId) => buildWeeks().some((w) => w.id === weekId);
const isValidCountry = (countryId) =>
  COUNTRIES.some((c) => c.id === countryId) ||
  getCustomCountries().some((c) => c.id === countryId);

function checkUploadCutoff(weekId) {
  const cutoff = weekUploadCutoff(weekId);
  if (!cutoff) return null;
  if (new Date() > cutoff) {
    const err = new Error('Date limite d\'envoi dépassée');
    err.status_code = 423;
    err.body = 'Délai dépassé : les uploads pour cette semaine sont clôturés depuis dimanche 17h30.';
    return err;
  }
  return null;
}

/**
 * Authentifie une création d'upload TUS. La route /api/tus est montée AVANT
 * le middleware requireAuth (les body-parsers casseraient le protocole TUS),
 * donc l'auth DOIT se faire ici. Le client envoie son token de session dans
 * metadata.adminPassword (admin OU mot de passe global — voir api/index.js).
 * Fail-closed : si GLOBAL_PASSWORD est configuré, aucun token valide = 401.
 */
export function authorizeTusUpload(meta = {}) {
  const GLOBAL = process.env.GLOBAL_PASSWORD;
  const ADMIN = process.env.ADMIN_PASSWORD;
  const token = normalizeToken(String(meta.adminPassword || meta.appPassword || ''));
  const isAdmin = !!(ADMIN && token && safeEqual(token, normalizeToken(String(ADMIN))));
  if (!GLOBAL) return { ok: true, isAdmin }; // dev local sans mot de passe
  const isUser = !!(token && safeEqual(token, normalizeToken(String(GLOBAL))));
  return { ok: isAdmin || isUser, isAdmin };
}

/** Allowlist d'extensions — même règle que le chemin multer (lib/upload.js). */
export function validateTusExtension(name) {
  const ext = path.extname(String(name || '')).toLowerCase();
  return ALLOWED_EXTENSIONS.has(ext);
}

export const tusServer = new Server({
  path: '/api/tus',
  datastore: new FileStore({ directory: uploadsDir }),
  // Même plafond que le chemin multer des rushes (200 Mo par défaut,
  // surchargeable MAX_FILE_SIZE). Sans lui : remplissage disque illimité.
  maxSize: MAX_FILE_SIZE,
  namingFunction: (req, metadata) => {
    // UUID + timestamp pour l'unicité, MAIS on préserve l'extension
    // d'origine (allowlist uniquement — pas d'injection possible) : toute
    // la chaîne aval détecte le type par extension (INLINE_EXT du static,
    // IMAGE_EXT de ffmpeg, isImage de Remotion, mime du player). Un fichier
    // sans extension est traité comme vidéo → écran noir si c'était une
    // image, téléchargement forcé au lieu de lecture inline, etc.
    const ext = path.extname(String(metadata?.filename || metadata?.name || '')).toLowerCase();
    const safeExt = ALLOWED_EXTENSIONS.has(ext) ? ext : '';
    return `${Date.now()}-${uuidv4()}${safeExt}`;
  },
  onUploadCreate: async (req, res, upload) => {
    // Authentification & Validation
    const meta = upload.metadata || {};
    const weekId = meta.weekId;
    const countryId = meta.countryId;

    const { ok, isAdmin } = authorizeTusUpload(meta);
    if (!ok) {
      throw { status_code: 401, body: 'Session requise : mot de passe invalide ou manquant.' };
    }

    if (!isValidWeek(weekId) || !isValidCountry(countryId)) {
      throw { status_code: 404, body: 'Week ou Country invalide' };
    }

    if (!validateTusExtension(meta.name || meta.filename)) {
      throw { status_code: 415, body: 'Type de fichier non autorisé.' };
    }

    if (!isAdmin) {
      const cutoffErr = checkUploadCutoff(weekId);
      if (cutoffErr) throw cutoffErr;
    }

    return res;
  },
  onUploadFinish: async (req, res, upload) => {
    const meta = upload.metadata || {};
    const weekId = meta.weekId;
    const countryId = meta.countryId;
    const filename = upload.id; // Generated by namingFunction
    const originalName = meta.name || 'Unknown.mp4';
    const reportage = meta.reportage || null;
    const fileType = meta.filetype || 'application/octet-stream';
    const fileSize = upload.size;

    const isScript = fileType.startsWith('text/') || fileType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    const isImage = fileType.startsWith('image/');
    const isAudio = fileType.startsWith('audio/');

    const fileData = {
      id: uuidv4(),
      name: originalName,
      filename: filename,
      type: isScript ? 'script' : isImage ? 'image' : isAudio ? 'audio' : 'video',
      size: `${(fileSize / (1024 * 1024)).toFixed(1)} MB`,
      status: 'pending',
      reportage,
      uploadedAt: new Date().toISOString(),
    };

    try {
      addUpload(weekId, countryId, fileData);
      recordUpload(1000, true); // Mock duration since we don't have start time across chunks
      logger.uploadReceived(weekId, countryId, originalName, fileData.size);

      logger.info('TUS Upload completed and persisted', {
        context: {
          weekId,
          countryId,
          filename: originalName,
          fileId: fileData.id,
          type: fileData.type,
          size: fileData.size,
        },
      });

      broadcastNotification({
        title: 'Nouveau fichier reçu',
        body: `Un fichier a été envoyé via l'envoi sécurisé par ${countryId} pour la semaine ${weekId}.`,
        url: `/?week=${weekId}`
      }).catch(err => logger.error('Push notification failed', { error: err.message }));

      io?.emit('upload_update', { weekId, countryId });

    } catch (storeErr) {
      logger.uploadFailed(weekId, countryId, originalName, storeErr);
      // Clean up file if DB fails
      const filePath = path.join(uploadsDir, filename);
      if (existsSync(filePath)) {
        unlinkSync(filePath);
      }
    }
    return res;
  }
});
